name: shopify-b2b-leads-${NODE_ENV}
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:3000
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SHOPIFY_APP_URL=${SHOPIFY_APP_URL}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - SCOPES=${SCOPES}
      - SHOPIFY_MY_WEB_PIXEL_ID=${SHOPIFY_MY_WEB_PIXEL_ID}
  db:
    hostname: db
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data # persist data
