name: shopify-b2b-leads-${NODE_ENV}
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:3000
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
