# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "557899d6cfece8282f869e9c39f08403"
application_url = "https://shopify-b2b-leads.glowsoft.de"
embedded = true
name = "B2B Leads"
handle = "b2b-leads"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://shopify-b2b-leads.glowsoft.de/auth/callback",
  "https://shopify-b2b-leads.glowsoft.de/auth/shopify/callback",
  "https://shopify-b2b-leads.glowsoft.de/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
