name = "b2b-leads-web-pixel"
type = "web_pixel_extension"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.apiURL]
name = "API URL"
description = "The URL of the B2B Leads API"
type = "single_line_text_field"
validations =  []
