name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        default: production
        required: true
        type: string
    secrets:
      SHOPIFY_API_KEY:
        required: true
      SHOPIFY_API_SECRET:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true
      SSH_KEY:
        required: true
      ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment
        options:
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Shopify CLI
        run: npm install -g @shopify/cli@latest
      - name: Deploy Shopify app
        run: shopify app deploy -f -c ${{ inputs.environment }} --source-control-url "$COMMIT_URL"
        env:
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script_stop: true
          script: |
            cd ~/apps/b2b-leads/${{ inputs.environment }}/b2b-leads-poc
            git pull https://kadruko:${{ secrets.ACCESS_TOKEN }}@github.com/kadruko/b2b-leads-poc
            docker compose build
            docker compose up -d
            docker system prune -af
