name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy to Production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets:
      SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
      SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
